# Generated by Django 3.0.4 on 2020-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200325_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.CharField(default=3, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.CharField(max_length=32),
        ),
    ]
