# Generated by Django 3.0.4 on 2020-03-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200326_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
